export { default as NavBar } from './nav-bar.svelte'
export { default as Landing } from './landing.svelte'
export { default as About } from './about.svelte'
export { default as Skills } from './skills.svelte'
export { default as Portfolio } from './portfolio.svelte'
export { default as Footer } from './footer.svelte'